#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

mv info.csv info1.csv
mv log.CavBubbleFsiFoam log1.CavBubbleFsiFoam

runApplication $application

# ----------------------------------------------------------------- end-of-file
