#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

mv log.decomposePar log1.decomposePar
mv log.decomposePar.solid log1.decomposePar.solid
mv log.CavBubbleFsiFoam log1.CavBubbleFsiFoam

sed -i 's/value           uniform 1/value           uniform 0/' 0/alpha1
runApplication ../../initSecondBubble/initbubble
sed -i 's/value           uniform 0/value           uniform 1/' 0/alpha1

mkdir tmp
mkdir ../solid/tmp
for proc in proc*
do
    mkdir tmp/$proc
    mkdir ../solid/tmp/$proc
    mv $proc/constant tmp/$proc
    mv ../solid/$proc/constant ../solid/tmp/$proc
done
rm -R proc*
rm -R ../solid/proc*

runApplication -l log.decomposePar.solid decomposePar -case ../solid -cellDist
runApplication decomposePar -cellDist

for proc in proc*
do
    mv tmp/$proc/constant $proc
    mv ../solid/tmp/$proc/constant ../solid/$proc
done
rm -R tmp
rm -R ../solid/tmp

runApplication decomposePar -cellDist

cd ..
./makeLinks fluid solid

# Build setInletVelocity function object
# wmake libso setInletVelocity

cd fluid

runParallel $application 8

# ----------------------------------------------------------------- end-of-file
