#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

refineMeshByCellSet()
{
   while [ $# -ge 1 ]
   do
      echo "creating cell set for primary zone - $1"
      cp system/cellSetDict.$1 system/cellSetDict
      runApplication -l log.cellSet.$1 cellSet

      echo "refining primary zone - $1"
      runApplication -l log.refineMesh.$1 refineMesh -dict -overwrite
      shift
   done
}

./Allclean
touch fluid.foam

cp -r 0.org 0

runApplication -l log.blockMesh.solid blockMesh -case ../solid
runApplication -l log.setSet.solid setSet -case ../solid -batch ../solid/setBatch
runApplication -l log.setToZones.solid setsToZones -case ../solid -noFlipMap

runApplication blockMesh

refineMeshByCellSet 1 2 3 4
cd ../solid
refineMeshByCellSet 1 2 3 4
cd ../fluid

runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

sed -i 's/value           uniform 1/value           uniform 0/' 0/alpha1
runApplication ../../initEllipse3D/initbubble
sed -i 's/value           uniform 0/value           uniform 1/' 0/alpha1

cd ..

./makeLinks fluid solid

cd fluid

runApplication $application

# ----------------------------------------------------------------- end-of-file
 
